# Generated by Django 2.2.10 on 2021-04-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=50)),
                ('firstappointment', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
